version: "3"

services:
  mail:
    image: greenmail/standalone:2.1.8
    ports:
      - "3025:3025" # SMTP
      - "3143:3143" # IMAP
      - "3465:3465" # SMTPS
      - "3993:3993" # IMAPS
      - "8080:8080" # API
    environment:
      - GREENMAIL_OPTS=-Dgreenmail.setup.test.all -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.auth.disabled -Dgreenmail.verbose
